### ISSUE TITLE
Don't save consultations when there are no details

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/uclp-tb#166]
e.g. editing an assessment pathway

**Comment by fredkingham** [comment]
this is done, we've manually put pathway logic in in both places we use patient consultation.

Ideally this would not be the case but we can't use our generic don't post empty data logic because of the defaults.

Long term solution is potentially using a form controller presave or an item presave, we don't have this functionality yet, so I'm marking as complete (as it does already work)
